#!/bin/bash

# Copyright (C) 2021 Pawel Soja <kernel32.pl@gmail.com>

# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.

# TODO List:
# - unit tests
# - packages for other distros
# - build via docker
# - safe run script path
# - run script via wget/curl

set -e

# Helpers
command -v realpath >/dev/null 2>&1 || realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

command -v nproc >/dev/null 2>&1 || function nproc {
    command -v sysctl >/dev/null 2>&1 && sysctl -n hw.logicalcpu || echo "3"
}

pushd() {
    command pushd "$@" > /dev/null
}

popd() {
    command popd "$@" > /dev/null
}

# Default
PREFIX=/usr/local
JOBS=$(($(nproc)+1))
SRCS=$(dirname $(realpath $0))/..
FIX_WARNINGS=ON
BUILD_UNITTESTS=ON
ROOT=$PWD

# Help message
help () {
    echo "Usage: $0 OPTION ... MODULE ..."
    echo
    echo "Options:"
    echo "  -c, --clean                 Remove output directory before build."
    echo "  -b, --build                 Build modules."
    echo "      --build-deb             Build debian packages."
    echo "  -j N, --jobs N              Allow N jobs at once. Default: ${JOBS} for your system."
    echo "  -p PREFIX, --prefix PREFIX  Install directory used by install."
    echo "  -i, --install               Install build or packages."
    echo "      --type TYPE             Build type."
    echo "  -r, --requisites            Install all needed requisites."
    echo "  -l, --list                  List available modules."
    echo "      --all                   Select all modules."
    echo "      --all-libs              Select all libs."
    echo "      --all-drivers           Select all drivers."
    echo "  -h, --help                  Prints this message."
    echo
    echo "Examples:"
    echo "  Install all requisites (Ubuntu):"
    echo "  $0 --build-deb --requisites"
    echo
    echo "  Install requisites:"
    echo "  $0 --requisites"
    echo
    echo "  List availiable modules:"
    echo "  $0 --list"
    echo
    echo "  Build selected debian packages (Ubuntu):"
    echo "  $0 --build-deb libasi indi-asi"
    echo
    echo "  Build all debian packages (Ubuntu):"
    echo "  $0 --build-deb --all"
    echo
    echo "  Build selected sources and install:"
    echo "  $0 --build --install libasi indi-asi"
    echo
    echo "  Build all and install:"
    echo "  $0 --build --install --all"
    echo
    echo "  Do everything and install via packages (Ubuntu):"
    echo "  $0 --requisites --clear --build --build-deb --install --all"
    echo
    echo "Warning!"
    echo "  To build, make sure you have INDI Core Library installed."
    echo
    exit 1
}

[[ $# -eq 0 ]] && help

imake_list_libs () {
    rm -rf $ROOT/build/indi-3rdparty-check-libs 1>&2
    mkdir -p $ROOT/build/indi-3rdparty-check-libs 1>&2
    pushd $ROOT/build/indi-3rdparty-check-libs 1>&2
    cmake -DBUILD_LIBS=1 . $SRCS 1>&2
    echo "$(\ls -d */ | sed 's#/##' | grep -v CMakeFiles | sort)"
    popd 1>&2
    rm -rf $ROOT/build/indi-3rdparty-check-libs 1>&2
}

imake_list_drivers () {
    rm -rf $ROOT/build/indi-3rdparty-check-drivers 1>&2
    mkdir -p $ROOT/build/indi-3rdparty-check-drivers 1>&2
    pushd $ROOT/build/indi-3rdparty-check-drivers 1>&2
    cmake -DBUILD_LIBS=0 . $SRCS 1>&2
    echo "$(join -v 1 <(\ls -d */ | sed 's#/##' | grep -v CMakeFiles | sort) <(imake_list_libs))"
    popd 1>&2
    rm -rf $ROOT/build/indi-3rdparty-check-drivers 1>&2
}

# list () {
#     ls $SRCS/*/CMakeLists.txt | grep -oP '(?<=/)indi-[^/]+(?=/CMakeLists.txt)'
# }

install_googletest () {
    echo "Installing googletest..."
    if [[ -v CLEAN ]]; then
        rm -rf $ROOT/build/googletest
    fi

    test -d googletest-src || git clone https://github.com/google/googletest.git $ROOT/googletest-src
    mkdir -p $ROOT/build/googletest
    pushd $ROOT/build/googletest
    cmake \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DBUILD_SHARED_LIBS=ON \
        . $ROOT/googletest-src
    make -j$JOBS
    $(command -v sudo) make install
    popd
}

install_deb_requisites () {
    echo "Installing debian package requisites..."
    OS=$(uname -s)
    
    case "$OS" in
        Linux)
            . /etc/os-release
            case $ID in
                debian|ubuntu|raspbian)
                    export DEBIAN_FRONTEND=noninteractive
                    # $(command -v sudo) apt-get update
                    # $(command -v sudo) apt-get upgrade -y
                    $(command -v sudo) apt-get install -y \
                        cdbs
                    ;;
                *)
                    echo "Cannot build debian package."
                    echo "System not supported: $ID"
                    cat /etc/os-release
                    exit 1
                    ;;
            esac
            ;;
        *)
            echo "Cannot build debian package."
            echo "System not supported: $OS"
            exit 1
    esac
}

install_requisites () {
    echo "Installing requisites..."
    # TODO
    # libtiff-devel ?

    OS=$(uname -s)

    case "$OS" in
        Darwin)
            brew install \
                git \
                cfitsio libnova libusb curl \
                gsl jpeg fftw \
                ffmpeg libftdi libraw libdc1394 libgphoto2 librtlsdr
            ;;
        Linux)
            . /etc/os-release
            case $ID in
                debian|ubuntu|raspbian)
                    export DEBIAN_FRONTEND=noninteractive
                    $(command -v sudo) apt-get update
                    $(command -v sudo) apt-get upgrade -y
                    $(command -v sudo) apt-get install -y \
                        git \
                        cmake build-essential zlib1g-dev \
                        libcfitsio-dev libnova-dev libusb-1.0-0-dev libcurl4-gnutls-dev \
                        libgsl-dev libjpeg-dev libfftw3-dev \
                        \
                        libftdi1-dev libavcodec-dev libavdevice-dev libavformat-dev libswscale-dev \
                        libgps-dev libraw-dev libdc1394-22-dev libgphoto2-dev \
                        libboost-dev libboost-regex-dev librtlsdr-dev liblimesuite-dev \
                        \
                        fxload
                    ;;
                fedora)
                    $(command -v sudo) dnf upgrade -y
                    $(command -v sudo) dnf install -y \
                        git \
                        cmake gcc-c++ zlib-devel \
                        cfitsio-devel libnova-devel libusb-devel libcurl-devel \
                        gsl-devel libjpeg-devel fftw-devel \
                        \
                        https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
                        https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

                    $(command -v sudo) dnf install -y \
                        ffmpeg-devel \
                        libftdi-devel \
                        gpsd-devel LibRaw-devel libdc1394-devel libgphoto2-devel \
                        boost-devel rtl-sdr-devel

                    ;;
                centos)
                    # CentOS 8 dont have libnova-devel package
                    $(command -v sudo) yum install -y epel-release
                    $(command -v sudo) yum upgrade -y
                    $(command -v sudo) yum install -y \
                        git \
                        cmake gcc-c++ zlib-devel \
                        cfitsio-devel libnova-devel libusb-devel libcurl-devel \
                        gsl-devel libjpeg-devel fftw-devel
                    ;;
                opensuse-tumbleweed)
                    # broken git/openssh package
                    $(command -v sudo) zypper refresh
                    $(command -v sudo) zypper --non-interactive update
                    $(command -v sudo) zypper --non-interactive install -y \
                        openssh git \
                        cmake gcc-c++ zlib-devel \
                        cfitsio-devel libnova-devel libusb-devel libcurl-devel \
                        gsl-devel libjpeg-devel fftw-devel libtheora-devel
                    ;;
                *)
                    echo "System not supported: $ID"
                    cat /etc/os-release
                    exit 1
                    ;;
            esac
            ;;
        *)
            echo "System not supported: $OS"
            exit 1
    esac
}

imake_all () {
    # Clean
    if [[ -v CLEAN ]]; then
        rm -rf $ROOT/build/indi-3rdparty
    fi

    # Configure
    mkdir -p $ROOT/build/indi-3rdparty
    pushd $ROOT/build/indi-3rdparty
    cmake \
        -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DFIX_WARNINGS=$FIX_WARNINGS \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
        -DINDI_BUILD_UNITTESTS=$BUILD_UNITTESTS \
        -DBUILD_LIBS=$1 \
        . $SRCS/$MODULE

    # Build
    if [[ -v BUILD ]]; then
        echo "Building libs..."
        make -j$JOBS
    fi

    # Install
    if [[ -v INSTALL ]]; then
        echo "Installing libs..."
        $(command -v sudo) make install
    fi
    popd
}

imake_from_list () {
    # Build, build package, install
    for MODULE in $@
    do
        # Clean
        if [[ -v CLEAN ]]; then
            rm -rf $ROOT/build/indi-3rdparty/$MODULE
        fi

        mkdir -p $ROOT/build/indi-3rdparty/$MODULE
        pushd $ROOT/build/indi-3rdparty/$MODULE

        # Configure
        cmake \
            -DCMAKE_INSTALL_PREFIX=$PREFIX \
            -DFIX_WARNINGS=$FIX_WARNINGS \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DINDI_BUILD_UNITTESTS=$BUILD_UNITTESTS \
            . $SRCS/$MODULE

        # Build
        if [[ -v BUILD ]]; then
            echo "Building ${MODULE}..."
            make -j$JOBS
        fi

        # Build deb package
        if [[ -v DEB ]]; then
            # Clean
            if [[ -v CLEAN ]]; then
                rm -rf $ROOT/build/indi-3rdparty-modules/$MODULE
            fi
            mkdir -p $ROOT/build/indi-3rdparty-modules/$MODULE
            pushd $ROOT/build/indi-3rdparty-modules/$MODULE
            echo "Packaging ${MODULE}..."
            cp -a $SRCS/$MODULE/ .
            cp -a $SRCS/debian/$MODULE/ ./debian/
            cp -a $SRCS/cmake_modules ./
            fakeroot debian/rules -j$JOBS binary &>/dev/null

            # Install deb package
            if [[ -v INSTALL ]]; then
                echo "Installing ${MODULE} from packages..."
                dpkg -i $(ls ../*.deb | grep -v dbg) || true
                #PKG_DBG=$(ls ../*.deb | grep  dbg)
                # [[ -n $PKG_DBG ]] && dpkg -i $PKG_DBG
            fi
            mkdir -p $ROOT/packages/
            mv ../*.deb $ROOT/packages/
            popd
        else
            # Install
            if [[ -v INSTALL ]]; then
                echo "Installing ${MODULE}..."
                $(command -v sudo) make install
            fi
        fi

        popd
    done
}

# Parse arguments
while [[ $# -gt 0 ]]
do
  case "$1" in
    -c|--clean)
        CLEAN=YES
        ;;
    -b|--build)
        BUILD=YES
        ;;
    --build-deb)
        DEB=YES
        ;;
    -i|--install)
        INSTALL=YES
        ;;
    -j|--jobs)
        shift
        JOBS="$1"
        ;;
    -p|--prefix)
        shift
        PREFIX="$1"
        ;;
    --type)
        shift
        BUILD_TYPE="$1"
        ;;
    --all)
        BUILD_ALL_LIBS=YES
        BUILD_ALL_DRVS=YES
        ;;
    --all-libs)
        BUILD_ALL_LIBS=YES
        ;;
    --all-drivers)
        BUILD_ALL_DRVS=YES
        ;;
    -l|--list)
        LIBS="$(imake_list_libs)"
        DRVS="$(imake_list_drivers)"
        echo
        echo "Available libraries:"
        echo $LIBS
        echo
        echo "Available drivers:"
        echo $DRVS
        echo
        echo "If the driver is missing, install the necessary libraries."
        exit 1
        ;;
    -r|--requisites)
        REQUISITES=YES
        ;;
    -h|--help)
        help
        ;;
    *)
        POSITIONAL+=("$1")
        ;;
  esac
  shift
done

set -- "${POSITIONAL[@]}"

# Requisites
if [[ -v REQUISITES ]]; then
    install_requisites
    [[ -v DEB ]] && install_deb_requisites
    install_googletest
fi

# Build all
if ( [[ -v BUILD_ALL_LIBS ]] || [[ -v BUILD_ALL_DRVS ]] ) && [[ ! -v DEB ]]; then
    [[ -v BUILD_ALL_LIBS ]] && imake_all 1
    [[ -v BUILD_ALL_DRVS ]] && imake_all 0
    exit 0
fi

# Build module by module
if [[ -v BUILD_ALL_LIBS ]]; then
    echo "Build all libs."
    imake_from_list $(imake_list_libs)
fi

if [[ -v BUILD_ALL_DRVS ]]; then
    echo "Build all drivers."
    imake_from_list $(imake_list_drivers)
fi

# Build others
if [[ $# -gt 0 ]]; then
    imake_from_list $@
fi
